encryptionsalt: v1:Kh95PlThgl8=:v1:IuAgB47DqFRaUIFn:I6VWB2Q7mFCkC9c1kViRyHIA2hLqCg==
config:
  vultr:apiKey:
    secure: v1:rSgL8QWeDdrdMMka:C1d8bvy4EGlUcrteS3sRpJ6RKJQ5NJ9WPgIPhXrtUVTP8FQrDjlZwdtZO1x26xbimz2m0w==
  stream-infra:allowedIngressIp: 58.84.142.60/32
  stream-infra:rtmpConfig:
    secure: v1:oJcHNZU4wOrmJRZS:wOm4C4c3gN2/z9o/IiZr0nza4AjbMfxARwnqepP7/5vaf4LYOpLVBcaRz3dTJZvL9Sxt+9S//sxz17RZcWQtRgC5Y0VGe1oEFYKQ98P+m3IQsezm+aedefAHLXFcR4biBHc2oDTmy9xo4gnKvKizS8zWwJfxWBwnZNA2K0+Lzzh17i1SkrgXiFsHX4pFIzu8FmPC1tErYyjvBDFkYdU4ywwBSpUgzOtAAlPFs16xHxckeXMnV8AYr1sgPHduE5LSXgvsdBmi3yx8cgyVSaSbWSu8MHPs94eejQZt+1Uv9vtUXreEMLq8s5iGhxANZ97pKu7JTvvcsYROJT3x+q+mXiwa8LqgswIPbq2XHhW8JhVkRLKxtQOWnArQL2nABAtjx+Zw65Z61kEQE2KYkjXe7p2YR1CP22Gyt5eEC/6VkMFoO44uSsqA9/AmEv8fe3Wdkiq8SrX2+Lh2GQaOd8e8l4Zm6hcxinWDVt+b8IwQGmoxeDMY23KH4W65H41WhJQXaptpxX5PxvKkRVD2DCqGMXvy6PJFNiXBDjrhevtAck4npGc13cCxU1xc8nRdNs2fHXFMI8Fp4vX+P8KM/asQqZ+1QMrhARjFcM0v3xppHRZjobLggysFiOEg7e52ceOVoEW1LZ7e9YPQYf3FjDyh1GP/iXNYm48woB/UabGUsiBNTCCMztLEpsDBphf+tSRpJiGEYFmjL2W81i/tfWhizXzHHb3jRkhkWhTk9yeJ2ZYEfls169EsiV+ZMujfnx0TQe8AHmHziVQQLmn994Xw1lT3aepON4XYYKlvCBKvh1nYGNe8qHm38Tgi15bZIDsxEzjIUTa9bG8OP8y2sevOF78fvw09c2PIJuxOeAMnhIcCkRmNnrVfEoTE6EhkFypd
  stream-infra:ddnsPassword:
    secure: v1:FRlRnPnRxWeMOfp0:601g1/bl3q+LzFxa7BG0o4unIxwY65fhDIhA8edEFyyvlrMUsVjqTuiE9ltd76W4
  stream-infra:ddnsDomain: vsyrakis.dev
  stream-infra:ddnsHost: rtmp
