encryptionsalt: v1:Kh95PlThgl8=:v1:IuAgB47DqFRaUIFn:I6VWB2Q7mFCkC9c1kViRyHIA2hLqCg==
config:
  vultr:apiKey:
    secure: v1:rSgL8QWeDdrdMMka:C1d8bvy4EGlUcrteS3sRpJ6RKJQ5NJ9WPgIPhXrtUVTP8FQrDjlZwdtZO1x26xbimz2m0w==
  stream-infra:allowedIngressIp: 58.84.142.60/32
  stream-infra:rtmpConfig:
    secure: v1:smODlaa6R6rzzHvP:QRDL8NBhLAJMHLL0/wEOMUCLNgif5uiJfizfPUsw6jxJFpTaW2YeUugxEeLMRFhrH7SS87atdwQ9GzGwtLb4WHbzgfiuO16NtjlPk01xHBwHaxOIH/BUEZUKpeEkubQTpqU3JDE0Uet6aV/5FHUu61iS14AzqEVMTD3YPrN1AecfmW6e7VRW3Oar84rqcSsULHjfKuOTKJMqE9dk73Xxj3XPVOgpSbrLk2yDfOU4vMIkqNUnTUrvxuKzzHdneKEc3qq5gaUxWpqzxfHLy5P75r9Mr1WAfBKP/t+tc860ib4Z1e4Waav1KKaOlOhzH1OKyKCgeQcaL0vabJLLazlkAfSuHjBU+hQGms7zyMb7M7Q3apzmfXi6DRWbx/0IHpl7LNQ6iSbBxV+34oxfcbhBR22a6tZ0sXYf8rX/VGNqAtuDR2yVqHhi5hr49UlG2wiqcREyq9RE3bUCjZq3ZDQ0ABUJ1r24knLvIQcevk90801ffeL8k1JHB7/VuQ3swz+wR5cp8e1c+HZ4lb7hAetJgoHFB+HxVAEdwPgHUG7ssRmxi9JQObLnKp8QYSGt1Q4PglP6RZuxwl2GekYrPu8f9vZ8O6Rp/xdsONF12M2c5ZLJRz+KWsQEGhRx5A==
