encryptionsalt: v1:Kh95PlThgl8=:v1:IuAgB47DqFRaUIFn:I6VWB2Q7mFCkC9c1kViRyHIA2hLqCg==
config:
  vultr:apiKey:
    secure: v1:rSgL8QWeDdrdMMka:C1d8bvy4EGlUcrteS3sRpJ6RKJQ5NJ9WPgIPhXrtUVTP8FQrDjlZwdtZO1x26xbimz2m0w==
  stream-infra:allowedIngressIp: 58.84.142.60/32
  stream-infra:rtmpConfig:
    secure: v1:kn5jXUgjCvBSx2yK:LBUmM2/ZZ/XSKcXl9WSMFLsrh4AOdIo6QmInXF/c+dl80ROW1hUCw8TBd8FNzhuypvQLJXBvbv5SaL+srWffAIvJZlQCwWAm+roQXXzGxTFftwU2npK38X1tttVFfp/HPkpWtwfO0HJ7HR4ulnwZOSbVOh9ZuxMSm6dU2BOaPIIXu1FJt1S1edH9pichLbvIi43SMOhW4Y/HhUz0920LZBTswoGzdCFIgG7DGdLEVERCnRFPRkXDUJH27qvmMa2bH+asxvgI0IDh1v+J6lQTDMssRy3lGfg5/RBjUkCTatfVNd8kCuUnrDHAWzy2tdPoqLScD2IRcVVrgwbLEuWlPN10HZKu7Lk0T0XQBoRm3rXD0HXXbEt/u27Ov/pyEoP7UW8BXNJW+kNLvOLL9WuiEDxDqAZWwv1xsovLYpp4ZYTyO52mfwAVV16u9uS5iU/f6x542rrJ4VOFzSthBFI/ZaBjkxGzHfkD/7neo6/Wo9o6nJjmGiQP5iUREZ14k/DDOiz7BzDQpXk/61OPwvyeHED9W7rmrtht/vX1EEtqvjrekOgJVeHz3Y/Rcxdqghf7iebzjxHyrNu3LCUMdUY+fkDgoCILoYddjUIn/XPOSAWUyPykM/YOemq2Fw==
